galaxy_image_tag: "dev_v17.09-pheno-lr_cv1.6.184"
galaxy_init_image: "container-registry.phenomenal-h2020.eu/phnmnl/galaxy-init-pheno-flavoured"
galaxy_image: "container-registry.phenomenal-h2020.eu/phnmnl/galaxy-web-k8s"
galaxy_res_limits_cpu: "2"
galaxy_res_limits_memory: "2Gi"
galaxy_res_requests_cpu: "500m"
galaxy_res_requests_memory: "500Mi"
proftpd_image: "container-registry.phenomenal-h2020.eu/phnmnl/galaxy-proftpd"
proftpd_image_tag: "for_galaxy_v17.09"
proftpd_port: 44
