- name: copy helm yaml template for Galaxy
  template:
    src: galaxy-helm-values.yaml.j2
    dest: ~/galaxy-helm-values.yaml

- name: add galaxy repo
  command: >
    helm repo add galaxy-helm-repo
      https://pcm32.github.io/galaxy-helm-charts

- name: install galaxy
  command: >
    helm upgrade --install -f ~/galaxy-helm-values.yaml
      --version "{{ galaxy_chart_version }}" "galaxy-stable" galaxy-helm-repo/galaxy-stable
  no_log: "{{ nologging }}"

- name: expose proftpd on desired port
  become: yes
  command: >
    iptables -t nat -A PREROUTING -p tcp -i "{{ hostvars[inventory_hostname].ansible_host }}" --dport "{{ proftpd_port }}"
      -j REDIRECT --to-ports 30722
