---
- name: Pachyderm services
  hosts: master
  gather_facts: "no"
  vars:
    # Service version tags
    minio_version: "RELEASE.2018-01-18T20-33-21Z"
    os_storage_class: "object-store-sc"
    pachyderm_version: "1.6.6"
    etcd_version: "v3.2.7"

  tasks:
    # Minio
    - name: Minio
      include_role:
        name: roles/minio
      vars:
        minio_release_name: "{{minio_release_name}}"
        minio_pvc_size: "{{minio_pvc_size}}"
        minio_accesskey: "{{minio_accesskey}}"
        minio_secretkey: "{{minio_secretkey}}"
        minio_replicas: "{{minio_replicas}}"
        minio_tag: "{{minio_version}}"
        os_sc: "{{os_storage_class}}"

    # Pachyderm
    - name: Pachyderm
      include_role:
        name: roles/pachyderm
      vars:
        pachyderm_release_name: "{{pachyderm_release_name}}"
        minio_release_name: "{{minio_release_name}}"
        pachyderm_etcd_pvc_size: "{{pachyderm_etcd_pvc_size}}"
        pachyderm_minio_accesskey: "{{minio_accesskey}}"
        pachyderm_minio_secretkey: "{{minio_secretkey}}"
        pachyderm_tag: "{{pachyderm_version}}"
        etcd_tag: "{{etcd_version}}"
        os_sc: "{{os_storage_class}}"
